import { CONTACT_LINKS } from "./contact.js";

export const GENES = [
  {
    id: "about",
    region: "ABOUT",
    year: "NOW",
    name: "origin",
    sync: "BIO",
    hexes: 5,
    logo: "assets/origin.jpg",
    logoAlt: "Baran Çiftçi",
    logoFull: true,
    blurb:
      "Computer engineering student split between Torino and Istanbul. I write software, tinker with robots, and ship small games — learning by building, then building again.",
    facts: [
      ["Based in", "Torino · Istanbul"],
      ["Focus", "Software · Robotics · Games"],
      ["Studying", "Computer Engineering"],
    ],
  },
  {
    id: "alfred",
    region: "WORK",
    year: "2024",
    name: "aIfred",
    sync: "SOON",
    hexes: 4,
    logo: "assets/alfred-logo.jpg",
    logoAlt: "aIfred",
    blurb: "Local operator — talks on the machine. No cloud. Coming soon.",
    facts: [
      ["Type", "personal AI operator"],
      ["Status", "private · working on it"],
      ["Stack", "on-device · no API key"],
    ],
  },
  {
    id: "unimind",
    region: "WORK",
    year: "2025",
    name: "unimind",
    sync: "LIVE",
    hexes: 5,
    href: "https://unimind.consulting/",
    logo: "assets/unimind-logo.png",
    logoAlt: "unimind",
    blurb:
      "Personalized university rankings — build a ranking around your priorities: academics, cost, outcomes, and fit.",
    facts: [
      ["Live", "unimind.consulting"],
      ["Focus", "university rankings · admissions data"],
      ["Role", "co-founder / developer"],
    ],
  },
  {
    id: "site",
    region: "WORK",
    year: "2026",
    name: "ciftci.dev",
    sync: "LIVE",
    hexes: 3,
    href: "https://ciftci.dev/",
    logo: "assets/ciftci-dev-logo.jpg",
    logoAlt: "ciftci.dev",
    blurb: "Personal site. Selected work.",
  },
  {
    id: "robotics",
    region: "WORK",
    year: "—",
    name: "robotics",
    sync: "LOCKED",
    hexes: 3,
    locked: true,
    logo: "assets/coming-soon-logo.jpg",
    logoAlt: "robotics",
    blurb: "Selected work — robotics. Coming soon.",
  },
  {
    id: "games",
    region: "WORK",
    year: "—",
    name: "games",
    sync: "LOCKED",
    hexes: 3,
    locked: true,
    logo: "assets/coming-soon-logo.jpg",
    logoAlt: "games",
    blurb: "Selected work — games. Coming soon.",
  },
  {
    id: "contact",
    region: "CONTACT",
    year: "NOW",
    name: "contact",
    sync: "OPEN",
    blurb: "GitHub, LinkedIn, Instagram — or write a line.",
    form: true,
    hexes: 4,
    links: CONTACT_LINKS,
  },
];

